### PR TITLE
refactor: update `emoji.json` now includes hex, dec and unicode along with removal of `AbstractEmoji` and expose `IEmoji`

### LINKED ISSUE #214: Issue in release mode
## Description of Bug

Hello just found an issue when `isMinifyEnabled = true`. The issue seems to be at the EmojiManager creation, for some reason the json doesn't get decoded. I have created a repo to showcase https://github.com/yoobi/emojifyreleaseissue

## Reproduction Steps

Start the app mode when `isMinifyEnabled = true` and the text just shows `:sweat_smile:` instead of the real emoji

### PR DESCRIPTION
**Pull request by wax911**
# AniTrend Pull Request

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/AniTrend/android-emojify/blob/develop/CONTRIBUTING.md) to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that add a new library or change existing tests, otherwise you risk spending a lot of time working on something that might not end up being merged into the project.

Before opening a pull request, please ensure you've done the following:

- You have followed our [**contributing guidelines**](https://github.com/AniTrend/android-emojify/blob/develop/CONTRIBUTING.md)
- Double checked that your branch is based on `develop` and targets `develop` (where applicable)
- Pull request has tests (if applicable)
- Documentation is updated (if necessary)
- Description explains the issue/use-case resolved

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (Improves existing functionality)

**IMPORTANT**: By submitting a patch, you agree to allow the project owners to license your work under the terms of the [Apache License 2.0](https://github.com/AniTrend/android-emojify/blob/develop/LICENSE.md).

### CODE REVIEW

**Comment by wax911** [comment]
@yoobi ready for review ⚡

**Comment by yoobi** [comment]
Neat PR, nothing more to add, really cool we don't need AbstractEmoji anymore :)

**Comment by yoobi** [comment]
Maybe I could commit on this branch to add `consumer-rules.pro` as to have a single release

**Comment by yoobi** [comment]
Oh we have committed at the same time, I'll close my PR, yours is better

**Comment by wax911** [comment]
> Oh we have committed at the same time, I'll close my PR, yours is better

Haha, whoops. I figured we might as well, I assumed you were busy so went ahead and added some. I don't think they're perfect and may need some fine tuning though. So fee free to suggest 😉

**Comment by yoobi** [comment]
I've had the same rules even less than what you did and it worked when I tried for all 3 serializers

**Comment by wax911** [comment]
> I've had the same rules even less than what you did and it worked when I tried for all 3 serializers

Great to hear, I'll merge this in. We can test the commit hash as our version and create a new release if you're happy with the outcome 😃

**Comment by yoobi** [comment]
I've tried checking `92bccf057a` but I get `Failed to resolve: com.github.anitrend.android-emojify:moshi:92bccf057a`

**Comment by wax911** [comment]
@yoobi not sure what the commit hash you're using points to but the latest commit hash on develop is e0369c5fae so you should be using https://jitpack.io/#anitrend/android-emojify/e0369c5fae -> `implementation 'com.github.anitrend.android-emojify:{module_here}:e0369c5fae'`

**Comment by yoobi** [comment]
Oh right, I was looking at jitpack builds and the last one was pointing at `92bccf057a `
I've tested the last version `e0369c5fae` and it seems to be working in my project with release mode

**Comment by wax911** [comment]
I'll hold off publishing the tag till Friday in case you uncover any issues

**Pull request merged**
